name: gwent_board
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher.png
